### ISSUE TITLE
Target is not set to _blank and Links to cross-origin destinations are unsafe in footer section 

### ISSUE THREAD

**Issue by Rupeshiya** [Ignitus/Ignitus-Client-Side-Development#110]
**Describe the bug**
 To improve performance and prevent security vulnerabilities of external links

**To Reproduce**
1. Go to 'https://github.com/Ignitus/Ignitus-Client-Side-Development/tree/master/src/ignitus-Footer/Components'
2. Click on 'footer.js'
3. Scroll down to 'community' section

**Expected behavior**
Add target="_blank" and add rel="noopener" or rel="noreferrer" to external links.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  express your view ?

**Comment by divyanshu-rawat** [comment]
@Rupeshiya go ahead 👍

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  since the issue is fixed so closing this issue.
