### ISSUE TITLE
External links is not provide in footer --> feature section.

### ISSUE THREAD

**Issue by Rupeshiya** [Ignitus/Ignitus-Client-Side-Development#111]
**Describe the bug**
href is not assigned any external links 

**To Reproduce**
1. Go to 'https://github.com/Ignitus/Ignitus-Client-Side-Development/tree/master/src/ignitus-Footer/Components'
2. Click on 'footer.js'
3. Scroll down to 'features' section

**Expected behavior**
href should be assigned with external links.
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  please give your view , I would like to fix this.

**Comment by divyanshu-rawat** [comment]
@Rupeshiya currently we are not pointing to any external URL. 
For Instance consider this code snippet.
Here as of now ```Opportunities``` section is under work! . So, we are not pointing it anywhere.
It not an issues as per my opinion.

```
<a className="link" href="#!">
     Opportunities
</a>
```
