### ISSUE TITLE
In navigation section cursor is not changing with respect to context.

### ISSUE THREAD

**Issue by Rupeshiya** [Ignitus/Ignitus-Client-Side-Development#112]
**Describe the bug**
When the pointer moves over Sign Up link it is not changing into a hand.

**To Reproduce**
1. Go to 'http://www.ignitus.org/'
2. Hover over 'Sign Up'
3. See error

**Expected behavior**
When the pointer moves over  Sign Up link it should change into a hand, indicating that the user can "click" the link.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  Please give your view , I would like to fix this .

**Comment by divyanshu-rawat** [comment]
yes @Rupeshiya go ahead 👍 .
It's a minor change waiting fot the PR.
