### ISSUE TITLE
Add React 16 ErrorBoundary

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#133]
Add React 16 ErrorBoundary, by leveraging react's new lifecycle Hook, componentDidCatch().

With error boundaries, even if one of your component’s results in an error, the entire react app would not get unmounted and instead only the erroneous component would display a fallback UI and the entire app would still be fully functional.

Error boundaries are React components that catch JavaScript errors anywhere in their child component tree, log those errors, and display a fallback UI instead of the crashed component tree.

**Comment by nirmalks** [comment]
I would like to work on this

**Comment by divyanshu-rawat** [comment]
@nirmalks go ahead 👍

**Comment by vvit5827** [comment]
I'm also working on this :smile:

**Comment by nirmalks** [comment]
I'm passing the issue up, since PR is already raised
