### ISSUE TITLE
Code-Splitting via React Loadable

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#137]
**Is your feature request related to a problem? Please describe.**

Bundling is great, but as our app grows, our bundle will grow too. Especially we you are including large third-party libraries. we need to keep an eye on the code we are including in your bundle so that we don’t accidentally make it so large that our app takes a long time to load.

To avoid winding up with a large bundle, it’s good to get ahead of the problem and start “splitting” our bundle. Code-Splitting is a feature supported by bundlers like Webpack and Browserify (via factor-bundle) which can create multiple bundles that can be dynamically loaded at runtime.

**Describe the solution you'd like**
Code-splitting oour app can help us “lazy-load” just the things that are currently needed by the user, which can dramatically improve the performance of your app, which in turn will reduce the amount of code needed during the initial load.

Create React App, this is already configured for you and you can start using it immediately. It’s also supported out of the box in Next.js.

**Describe alternatives you've considered**
We haven't considered any alternatives till so far, this is our first shot on top of that 👍 

**Additional context**
**React Loadable**

React Loadable wraps dynamic imports in a nice, React-friendly API for introducing code splitting into your app at a given component.

**Comment by masihtamsoy** [comment]
Hi, I want to pick this up. Is it available?

**Comment by divyanshu-rawat** [comment]
The main intention here is to lazyload some of the components that we won't need on intial rendering,  which in turn will reduce the amount of code needed during the initial load.

**Comment by divyanshu-rawat** [comment]
@masihtamsoy  I have added react-loadable in the last commit for Aboutus section feel free to improve it or do whatever you think is the right approac 👍

**Comment by masihtamsoy** [comment]
Starting with publicRoute.js file. You have wrapped react-Loader HOC around AboutUs component, it works. I was thinking to  wrap LoginProfessor, SignupProfessor and other components in `publicRoute` with good practise? I think all the parent component will be wrapped with Loader HOC, thoughts ?

**Comment by masihtamsoy** [comment]
Hi, I have created a Component level Loadable. `publicRoutes.js` have option to import either Sync component or Async component. Feedback?

**Comment by divyanshu-rawat** [comment]
@masihtamsoy Thanks for the PR 👍

**Comment by masihtamsoy** [comment]
@divyanshu-rawat What about other component in `publicRoute.js` should I create Loadable for them too?
