### ISSUE TITLE
Unexcpected behaviour of Signup button .

### ISSUE THREAD

**Issue by Rupeshiya** [Ignitus/Ignitus-Client-Side-Development#142]
**Describe the bug**
 On clicking Signup button (which is below Supporters & Partners ) it redirects to http://www.ignitus.org/signup.

**Expected behavior**
  It should give two options like as in navbar .Then after choosing one of them redirects accordingly.

@divyanshu-rawat  give your view.

**Comment by divyanshu-rawat** [comment]
@Rupeshiya Great catch even when you move to http://www.ignitus.org/signup you are able to see footer and header wihout any content in between👍

**Comment by divyanshu-rawat** [comment]
Kindlt tc of it @Rupeshiya 👍

**Comment by steaward** [comment]
@Rupeshiya you going to work on this? If not, I can do it.

**Comment by Rupeshiya** [comment]
@steward If you want to work on this go ahead but keep the points in mind .👍

**Comment by steaward** [comment]
Do you want the sign-up button to be a drop down? 
Or do you want it to be a link to an actual sign-up page(this is where the user can choose to sign up as a professor or a student)

**Comment by HankBrown** [comment]
I am steward. Never heard of this project until I got a notification.

Looking at the thread, I guess you want **steaward**.

**Comment by Rupeshiya** [comment]
> I am steward. Never heard of this project until I got a notification.
> 
> Looking at the thread, I guess you want **steaward**.

sorry @steward ,that was a typo .

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  closing this issue since fixed .
