### ISSUE TITLE
 Implement  signup for  professor 

### ISSUE THREAD

**Issue by Rupeshiya** [Ignitus/Ignitus-Client-Side-Development#150]
**Describe the Feature**
Login/Signup for Student has already been done.
We are looking forward to implement Login/Signup for professor as well.

We have a node.js based rest-api (https://github.com/Ignitus/Ignitus-rest-api) on the backend, having ``` /authentication ``` and ``` /registration ``` routes.
Feel free to use that api for implmenting Login/Signup for proeffesor on client side.

For reference you can also checkout client side Login/Signup for Student as well.
For any issue feel free to let us know 👍

**Comment by Rupeshiya** [comment]
Oh I did not knew that . @divyanshu-rawat

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  sigup above the footer is also not working now ,I don't know the reason but previously it was working ?

**Comment by divyanshu-rawat** [comment]
@Rupeshiya signup with student?

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  Nothings happen on clicking Signup button which is jsut above footer.

**Comment by divyanshu-rawat** [comment]
@Rupeshiya it is working fine, just tested it kindly follow - http://www.ignitus.org/signup/student and register with your email ID it will send you below mentioned confirmation, verify your email, then try logging it, you will be good to go.
![screenshot 2018-11-25 at 12 08 51 am](https://user-images.githubusercontent.com/13464678/48971916-82584500-f046-11e8-9b5d-0c13f7bdf6ad.png)

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  I am talking about this button .
![screenshot 84 _li](https://user-images.githubusercontent.com/31209617/48971952-0c081280-f047-11e8-91ed-3c3eac0ce357.jpg)

**Comment by divyanshu-rawat** [comment]
@Rupeshiya  oh sorry I misunderstood, as this issue was related to prof, signup I think this button needs to be fixed.

**Comment by Rupeshiya** [comment]
@divyanshu-rawat  Cool !!
