### ISSUE TITLE
Generate documentation for Ignitus :) 

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#151]
**Is your feature request related to a problem? Please describe.**
There's no doubt that project documentation is a vital part of project management. It is substantiated by the essential two functions of documentation: to make sure that project requirements are fulfilled and to establish traceability with regard to what has been done, who has done it, and when it has been done

**Describe the solution you'd like**
Use https://www.docz.site/ for the same.

**Additional context**
Using Docz's built-in components makes it easy to document your things. Using the power of components and AST parsing algorithms to source data, Docz renders your components on the fly, generates fully-formatted property tables, provides custom search, and so much more. The sky is the limit!

**Comment by debck** [comment]
thanks @divyanshu-rawat Can you please tell the subtopics that need to be included (or some example documentation ).  I had never written  any project documentation before 😄

**Comment by divyanshu-rawat** [comment]
@debck It generates it automatically I guess feel free to give it a try :) Let's see.
You can include subtopics as per your choices 👍

**Comment by divyanshu-rawat** [comment]
@debck  maybe you can also use your documentation experience here as well - https://docs.google.com/presentation/d/1ABqCc5uAoQv9aqGCxmNqOJ9S_Tst-adNV3fcWQ2Quwc/edit#slide=id.g42b115f18c_0_0

**Comment by divyanshu-rawat** [comment]
and for more info. refer this  [youtube](https://www.youtube.com/watch?v=5vG28udwfcA&index=1&list=PLMV09mSPNaQmFLPyrfFtpUdClVfutjF5G)  tutorial 👍
