### ISSUE TITLE
Scroll Effect when clicked on Navbar elements.

### ISSUE THREAD

**Issue by plxity** [Ignitus/Ignitus-Client-Side-Development#156]
**Is your feature request related to a problem? Please describe.**
 As to make Homepage better, We can add scroll effect on the NavBar elements. So instead of going directly to that section, we can add some effect during that transition.

**Describe the solution you'd like**
Using react-scroll npm module we can implement this functionality.

**Additional context**
Check this link for the module: - https://www.npmjs.com/package/react-scroll

**Comment by plxity** [comment]
Can I work on this?

**Comment by divyanshu-rawat** [comment]
@plxity go ahead 👍
