### ISSUE TITLE
Implement Navbar UI 

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#161]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI of Navbar in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://github.com/Ignitus/Ignitus-UI-Kit) for User-Interface and other styles related issue.

![screenshot from 2018-11-01 21-33-08](https://user-images.githubusercontent.com/26546816/47863644-c11b2680-de1d-11e8-9e55-bf5f8a3e8fbf.png)

**Comment by meyfleur** [comment]
i can go for it. Maybe also the footer too?

**Comment by divyanshu-rawat** [comment]
@meyfleur So, make it fixed then 😃.

**Comment by Paarmita** [comment]
@meyfleur Navbar should be fixed on the top. And the color scheme should be like this and not the triangle one. 
![screenshot from 2018-11-08 13-33-44](https://user-images.githubusercontent.com/26546816/48185437-fc0be580-e35a-11e8-96ca-a4859708d7f7.png)

**Comment by Paarmita** [comment]
@meyfleur or on scrolling the navbar should change to white background blue text and fixed on top.
