### ISSUE TITLE
Add Hover effect in Team UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#169]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI of Team on hover in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://github.com/Ignitus/Ignitus-UI-Kit) for User-Interface and other styles related issue.

![screenshot from 2018-11-09 00-55-27](https://user-images.githubusercontent.com/26546816/48222264-2d67ce00-e3ba-11e8-8acd-7ec69ecd6f7b.png)

**Comment by karagudisuma** [comment]
Hi,
   I was working on this issue in my local and I am able to display social media icons and enlarge the card on hover. Can you please assign the issue to me, can I raise PR for this?
Let me know if the issue is already fixed or any change in requirements.
-Suma

**Comment by karagudisuma** [comment]
Adding to message above, the /Ignitus-Client-Side-Development/src/ignitus-CoreTeam/Components/Data.js has facebook link for angellist key. It needs a change.  :)

**Comment by Paarmita** [comment]
@karagudisuma Thanks for looking into the issue. 🙂
You can send a PR for the issue, and we can then look if more changes are required.
Thanks for pointing out the error. So link has to be changed in it.

**Comment by karagudisuma** [comment]
Thanks. But when i try to push changes I am getting this error:
 Permission to Ignitus/Ignitus-Client-Side-Development.git denied to karagudisuma.
fatal: unable to access 'https://github.com/Ignitus/Ignitus-Client-Side-Development.git/': The requested URL returned error: 403

Is there any permissions required?
