### ISSUE TITLE
Align images in the box to center

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#173]
**Describe the solution you'd like**
Align the images for Partners in the middle of the box, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://github.com/Ignitus/Ignitus-UI-Kit) for User-Interface and other styles related issue.

![screenshot from 2018-11-11 13-51-37](https://user-images.githubusercontent.com/26546816/48310700-20fd9400-e5b9-11e8-8bbf-18856fc97b84.png)

**Comment by trblackw** [comment]
I'm going to look into this!

**Comment by Paarmita** [comment]
@trblackw Sure :)

**Comment by trblackw** [comment]
I've added an object-fit property to the images making them look a bit nicer, but what else are you looking for here? The images appear fairly centered as is.

**Comment by trblackw** [comment]
I accidentally left a console.log in there, my apologies

**Comment by Paarmita** [comment]
@trblackw it looks nicer now. I will also make dimensions for all images same so that they fit in the center and looks identical.

**Comment by trblackw** [comment]
I added the property to the contributors as well, but the effect was less
noticeable
