### ISSUE TITLE
Padding between two section will the UI/UX better.

### ISSUE THREAD

**Issue by plxity** [Ignitus/Ignitus-Client-Side-Development#176]
**Is your feature request related to a problem? Please describe.**
Padding between the first two section of the homepage will make it look better.

**Describe the solution you'd like**
We can add padding-top to make the UI better.

Original
![2018-11-12 2](https://user-images.githubusercontent.com/28510494/48366214-24853e00-e6d3-11e8-9f6c-5a19b3e85928.png)

After adding little padding
![2018-11-12 3](https://user-images.githubusercontent.com/28510494/48366244-3961d180-e6d3-11e8-9273-459d0ab2c5c0.png)

**Comment by Paarmita** [comment]
@plxity Do u want to take up this issue?

**Comment by plxity** [comment]
Yes sure!:)
