### ISSUE TITLE
improve mobile view 

### ISSUE THREAD

**Issue by Rupeshiya** [Ignitus/Ignitus-Client-Side-Development#184]
@Paarmita  plz look at the mobile view of our site ,and improve it.

**Describe the bug**
Images in the internship ,course etc sections are not responsive.

**To Reproduce**
Make images responsive.
**Expected behavior**
Images Should be flexible with size.

**Comment by aaditya1499** [comment]
Can I take up this issue and try to make the website fully responsive ?

**Comment by Paarmita** [comment]
@aaditya1499 Yes, Sure!

**Comment by aaditya1499** [comment]
I have made the pull request regarding the fix.

**Comment by Rupeshiya** [comment]
@aaditya1499  plz add a reference to your PR , so it will be easy to review .
