### ISSUE TITLE
Implement Dashboard UI

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#195]
**Is your feature request related to a problem? Please describe.**
We need to implement the Dashboard UI using static data for now.

**Describe the solution you'd like**
Implementation of attached UI Dashboard in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=0%3A1) for User-Interface and other style-related issues.

**Expected-Interface**

![screenshot from 2018-12-09 10-17-43](https://user-images.githubusercontent.com/26546816/49693537-b29df880-fb9b-11e8-94fd-fa260fce1bf1.png)

**Comment by karagudisuma** [comment]
Hi,
   Can I work on this?  If I can work, can you please point out where the design of this page is on the UI Toolkit. The image attached here is getting blurred on zooming.
-Thanks,
  Suma.

**Comment by Paarmita** [comment]
@karagudisuma You can view the designs here- https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=0%3A1
And we will be using material-ui components, so you need to start with this.

**Comment by karagudisuma** [comment]
Thanks, I will start working this week.

**Comment by Paarmita** [comment]
@karagudisuma Yes, Sure! Let me know if you have any questions.
Feel free to ask on the slack.
