### ISSUE TITLE
Add contributors to team from Ignitus-rest api repo

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#197]
As we added the contributors for Client-side in our [website](http://www.ignitus.org/aboutus), we also need to include the contributors of [Ignitus-rest api](https://github.com/Ignitus/Ignitus-rest-api/graphs/contributors).
You can take the example from:
https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/master/src/ignitus-Api/constants.js

**Comment by mpriyadarshini** [comment]
Hi, I want to work on this issue.

**Comment by Paarmita** [comment]
@mpriyadarshini Yes Sure 🙂
