### ISSUE TITLE
About Us link in the navbar redirect to team section

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#206]
**Describe the bug**
When clicked on the About us link in the navbar, it directs to the team component and not the About Us section.

**To Reproduce**
1. Go to 'About Us' on the navbar
2. Click on 'About Us'
3. Scroll up to 'About' section.

**Expected behavior**
It must take to the about section and not the team. 

**Screenshots**
![screenshot from 2018-12-24 18-23-45](https://user-images.githubusercontent.com/26546816/50400022-927c5500-07a9-11e9-91d2-733353f2d5b8.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by Aditya-Kolla** [comment]
Can I work on this?

**Comment by divyanshu-rawat** [comment]
@Aditya-Kolla sure go ahead 👍
