### ISSUE TITLE
Caching Github Api Calls

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#209]
**Is your feature request related to a problem? Please describe.**
Even if a new contributor is not added to the project, everytime when we move to `http://www.ignitus.org/aboutus` an api call is made to the `github server` in turn exhausting number of api calls allowed in an hour.

**Describe the solution you'd like**
No consumption of api calls until a new contributor is added, in summary if no new contributor is added to the project then it will keep on returning existing contributors from the `cache` instead of making an api call to fetch the contributors.

**Describe alternatives you've considered**
None till so far.

**Additional context**
Helpful: 

- https://stackoverflow.com/questions/14886664/caching-github-api-calls
- Headers like `(ETag, Last-modified, Cache-control)` will help.
- https://developer.github.com/v3/#conditional-requests

`Most responses return an ETag header. Many responses also return a Last-Modified header. You can use the values of these headers to make subsequent requests to those resources using the If-None-Match and If-Modified-Since headers, respectively. If the resource has not changed, the server will return a 304 Not Modified.`

**Comment by edubey** [comment]
I will look into this, let me come up with possible solutions. Will discuss it then.

**Comment by divyanshu-rawat** [comment]
@edubey that's great thank you 👍

**Comment by Aditya-Kolla** [comment]
I'm looking into the HTTP caching solution if that's okay.

**Comment by divyanshu-rawat** [comment]
@Aditya-Kolla do you really think will it work? even I think `localStrorage` is also there but the we need to minimize the number of calls, so I think optimum solution is to store them in the DB, not updating it until a new contributor is added, now hoe to figure out whether new contributor is added or not we can do it by making use different headers that github provide. We can write the api calls in our rest api to achieve the same. but sitill if it is possible without doing what I have mentioned till so far, then I would be great thanks @Aditya-Kolla looking forward to your approach 😄 . cc @edubey what do you think about the solution proposed by @Aditya-Kolla :)

**Comment by edubey** [comment]
Github Provides us Header to use and **conditional request returns 304 response but not results.** . They want service consumer to implement caching using these headers

Now we can have two implementation. User browser which is simple but still we will have good number of hits considering no of browser user uses. Also questions comes is when do you validate invalidate localstorage value and where do you store contributers list (also in localstorage). I had done such implementation, it comes with own challenges.

From DB point, my initial thought is storing github caching header like E-tag in DB and contributer's list. Every time a user navigates to the website we use these E-tag to validate and update DB with e-tag / contributers list if response if 200 not 304. This should reduce the api call limit
@divyanshu-rawat @Aditya-Kolla

**Comment by CDharmateja** [comment]
After looking into this, I found that the browser by default caches the requests with ETag and re-validate them after the max-age which is provided with `Cache-Control` header. So even if we use a local db, we are doing the same thing. But a local db like indexedDB is useful when the website is offline-first. If we make it offline-first with service worker, then we can show contributors list to users even when a user is offline.

**Comment by divyanshu-rawat** [comment]
@CDharmateja are you willing to work on this ?

**Comment by CDharmateja** [comment]
@divyanshu-rawat  Yeah. I will work on it.

**Comment by divyanshu-rawat** [comment]
Thanks 👍 good luck then @CDharmateja 🚀.

**Comment by CDharmateja** [comment]
Thanks @divyanshu-rawat . I have accepted the invite yesterday. Can you also please add gssoc19 label to this issue?

**Comment by divyanshu-rawat** [comment]
sure @CDharmateja 👍

**Comment by CDharmateja** [comment]
@divyanshu-rawat  I am almost done implementing this GitHub API calls. We are also make API Call for testimonials. The ignitus API i.e., `https://ignitusrestapi.herokuapp.com/testimonials` also returning `ETag` but the server need to set the header `Access-Control-Expose-Headers: ETag` in order to access the `ETag` from axios.

**Comment by divyanshu-rawat** [comment]
COOL @CDharmateja I can set the header once I get spare time. or if you want you can also set the header, here is the server-side repo. https://github.com/Ignitus/Ignitus-rest-api.
I will review you merge-request today.
Thanks ⚡️
