### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#21]
Travis CI is a hosted, distributed continuous integration service used to build and test software projects hosted at GitHub. Open source projects may be tested at no charge via travis-ci.org.

Adding .travis.yml will do the job.  👍

**Comment by debck** [comment]
can u please describe what do you want to do in this issue as the travis.yml file is already there.

**Comment by Paarmita** [comment]
@debck Thanks! yeah, It was added earlier. You can try some other issue.
