### ISSUE TITLE
Footer too long in mobile view.

### ISSUE THREAD

**Issue by plxity** [Ignitus/Ignitus-Client-Side-Development#221]
**Describe the bug**
Size of the footer is too much in mobile view

**To Reproduce**
1. Go to http://www.ignitus.org in mobile view

**Expected behavior**
Only limited information should be present in the footer to make it look better.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Paarmita** [comment]
@plxity Would you like to work on this issue?

**Comment by plxity** [comment]
Yes sure @Paarmita

**Comment by lazycipher** [comment]
@plxity any update?
@Paarmita Should I work on this?
