### ISSUE TITLE
Implement What we provide? UI 

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#226]
**Is your feature request related to a problem? Please describe.**
We need to implement the given UI as the new version is improved.

**Describe the solution you'd like**
Implementation of attached UI What we provide? in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://www.figma.com/file/BrP5RowC7va50HyETZQUDA/Ignitus-Design?node-id=0%3A1) for User-Interface and other style-related issues.

**Expected-Interface**
![screenshot from 2019-01-02 20-13-27](https://user-images.githubusercontent.com/26546816/50596629-e59d8880-0eca-11e9-8519-052d2168ba11.png)

**Comment by karagudisuma** [comment]
Hi @Paarmita,
  Is this issue open? If so can you please give more details as to what has to be done. I see the section implemented as Card component. What is the improvisation required here? I would like to take up this if I can understand what has to be done.
-Thanks,
 Suma

**Comment by Paarmita** [comment]
Hey @karagudisuma, 
The present design is not up to the card styles that we are following now. As you can see as the position of section and card style are changed. 
To have more insights on the issue you can look in the Figma design- https://goo.gl/SPCSCh.

**Comment by karagudisuma** [comment]
Sure, got it. I will do the changes and raise PR.
