### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#23]
Dockerizing an application is the process of converting an application to run within a Docker container. While dockerizing most applications is straight-forward, there are a few problems that need to be worked around each time.

Please follow the thread to know more 👍

- https://mherman.org/blog/dockerizing-a-react-app/
- https://medium.com/@thexap/how-to-dockerize-your-reactjs-app-ad618a48ad6b

**Comment by debck** [comment]
I want to work on this isssue

**Comment by Paarmita** [comment]
@debck Sure! Go ahead.

**Comment by divyanshu-rawat** [comment]
@debck it is failing travis ci, so kindly look at the log and figure out the reaseon why it is failing?
