### ISSUE TITLE
Add Istanbul Code Coverage

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#24]
Istanbul instruments your ES5 and ES2015+ JavaScript code with line counters, so that you can track how well your unit-tests exercise your codebase. 👍

Please follow the resource to know more 👍

- https://istanbul.js.org/docs/tutorials/jest/

**Comment by divyanshu-rawat** [comment]
Sure it's great 👍

**Comment by vindu939** [comment]
@divyanshu-rawat since I don't see any pull request for this so far, I am raising one

**Comment by debck** [comment]
As the PR is merged so the issue should be closed @divyanshu-rawat
