### ISSUE TITLE
Join link in navigation bar is not active anymore

### ISSUE THREAD

**Issue by plxity** [Ignitus/Ignitus-Client-Side-Development#243]
**Describe the bug**
When a user clicks on "Join" in the navigation bar, It redirects to a link which is not active anymore

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://www.ignitus.org/'
2. Click on 'Join'

**Expected behavior**
Should redirect to a valid link.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Paarmita** [comment]
@plxity Updated the link!
