### ISSUE TITLE
Slack Invite Link in Readme is no longer active.

### ISSUE THREAD

**Issue by Yugandhartripathi** [Ignitus/Ignitus-Client-Side-Development#248]
**Describe the bug**
Slack invite link in Readme file is expired.

**To Reproduce**
1. Go to 'README.md'
2. Click on 'Link to Join Ignitus slack channel'
3. See error

**Expected behavior**
Redirect to Slack login/signup to join Ignitus channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/32102845/53299820-9c800a00-3865-11e9-8ec5-18d4e1bcfb58.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 72.0.3626.109

**Comment by divyanshu-rawat** [comment]
@Yugandhartripathi thanks for pointing this out 👍 , here is the new link (https://bit.ly/2SaYXMO)

**Comment by gittysachin** [comment]
@divyanshu-rawat the new link isn't working.
