### ISSUE TITLE
Add Redux

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#26]
Redux is an open-source JavaScript library for managing application state. It is most commonly used with libraries such as React or Angular for building user interfaces. Similar to Facebook's Flux architecture, it was created by Dan Abramov and Andrew Clark.

Please follow the resource to know more 👍 

- https://hackernoon.com/adding-redux-to-a-react-blog-97f5fea606c2

**Comment by shaminmeerankutty** [comment]
@divyanshu-rawat Can I help with this one?

**Comment by divyanshu-rawat** [comment]
@shaminmeerankutty go ahead 👍 :)
