### ISSUE TITLE
Background of navbar in mobile view

### ISSUE THREAD

**Issue by arc9693** [Ignitus/Ignitus-Client-Side-Development#285]
When clicked on the hamburger icon on the navbar, it expands displaying the links. The background of the expanded navbar is transparent and therefore the texts coincide and it's messy.

![Screenshot from 2019-04-13 02-23-08](https://user-images.githubusercontent.com/36061892/56065850-a61ced00-5d93-11e9-8dcc-a07ad5fcdf63.png)

Applying a solid background will solve the problem.

**Comment by Paarmita** [comment]
@arc9693 Thanks for opening the issue 😀Would you like to work on it?

**Comment by arc9693** [comment]
@Paarmita yes. Claiming.

**Comment by arc9693** [comment]
@Paarmita  can you please put the label 'gssoc19' on this issue?
