### ISSUE TITLE
Add Testimonials UI in React

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#29]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source contributors and current team attached UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI  in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer this for UI.

![screenshot from 2018-09-26 23-02-46](https://user-images.githubusercontent.com/26546816/46097741-49cff280-c1e0-11e8-9d8e-3a62556ebcdf.png)

**Comment by Trip4077** [comment]
I can work on this 🙂

**Comment by divyanshu-rawat** [comment]
@Trip4077 go ahead that's great 👍 even if you want you can suggest your own UI as well.
Or can take inspiration from other web applictions for  `testimonial UI` for instance `https://www.codementor.io/` etc.
