### ISSUE TITLE
Implement Landing page UI in React

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#30]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source contributors and current team attached UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI (Header, Footer, What we provide, Introduction) sections of Landing Page in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://github.com/Ignitus/Ignitus-UI-Kit) for User-Interface and other styles-related issue.

![landing page](https://user-images.githubusercontent.com/26546816/46717772-af16ef80-cc86-11e8-903e-b282fd55d226.png)

**Comment by manuelfs12** [comment]
I'll try to tackle this one.

**Comment by divyanshu-rawat** [comment]
@manuelfs12 It's Great if you want to try it. 👍 
Although you need to implement it from scratch like footer is already in there, but with a cahnge in color scheme, and testimonial are also there, you can go through the codebase to get more insights on the same.

**Comment by manuelfs12** [comment]
Will do, thanks.
