### ISSUE TITLE
Add filter for repeated usernames in Contributor's section

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#301]
**Describe the bug**
On the contributor's section, as contributors from 2 different repositories(Client and server) are rendered so there are some overlapping Github usernames.

**To Reproduce**
See profiles in this section

<img width="1163" alt="Screenshot 2019-04-22 at 9 08 34 PM" src="https://user-images.githubusercontent.com/26546816/56508786-cf333f80-6542-11e9-9f92-4a0a6afa8a03.png">

**Expected behavior**
We can add a filter to remove the repeated usernames.

**Comment by arc9693** [comment]
Claiming.

**Comment by arc9693** [comment]
@Paarmita can you please add a gssoc19 label?

**Comment by divyanshu-rawat** [comment]
@arc9693 added ⚡️
