### ISSUE TITLE
Implement Contributors and Partners UI in ReactJS

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#33]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source contributors and current team attached UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI of Contributors and Partners in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://github.com/Ignitus/Ignitus-UI-Kit) for User-Interface and other styles related issue.

![screenshot from 2018-09-29 10-56-17](https://user-images.githubusercontent.com/26546816/46241401-e4922200-c3d6-11e8-86fa-4540fa6f2462.png)

**Comment by sunilsj99** [comment]
Can you explain the issue ?? i would like to contribute !! @Paarmita

**Comment by Paarmita** [comment]
@sunilsj99 You need to implement this UI in React under each of the component folders for contributors and Partners.
