### ISSUE TITLE
Broken test and test coverage

### ISSUE THREAD

**Issue by edward-hong** [Ignitus/Ignitus-Client-Side-Development#354]
**Describe the bug**
Right now there's a broken test in `src/ignitus-Testimonial/selectors.test.js`

**To Reproduce**
Run command `npm run test`

**Expected behavior**
A passing test

**Screenshots**

![Screen Shot 2019-08-19 at 6 14 34 PM](https://user-images.githubusercontent.com/16217130/63242995-5902d780-c2ad-11e9-98cc-90b0f4c48429.png)

**Desktop (please complete the following information):**
I'm on a Mac Mojave, Chrome

**Additional context**
This issue can be fixed very easily. Here's the unit test:

```js
test('should return array of Testimonial data if it exists', () => {
      const data = [{
        content: 'My Content',
        author: 'John Smith',
        source: 'https://example.com',
      }];
      const testimonialState = [
        { data },
      ];
      const mockedState = {
        testimonialReducer: testimonialState,
      };
      expect(selector(mockedState)).toEqual(data);
    });
```

All it takes is declaring `const testimonialState = data` rather than `const testimonialState = [{ data }]` and the test will pass.

In a broader context, right now the code coverage is quite lacking:

![Screen Shot 2019-08-19 at 6 19 21 PM](https://user-images.githubusercontent.com/16217130/63243203-f100c100-c2ad-11e9-955c-e0328a36f9cd.png)

I want to write more tests to improve the robustness of this codebase and also improve my understanding of where everything is as a whole. I can create a quick PR for the broken test now and create an ongoing separate long term issue regarding code coverage.

**Comment by divyanshu-rawat** [comment]
@edward-hong  great go ahead 👍 , keep in mind only contribute if you have spare time :).

**Comment by edward-hong** [comment]
The individual unit test now passes with the PR I just made. I'll now create a new issue to improve code coverage.
