### ISSUE TITLE
ADD JEST/Enzyme

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#38]
Adding Unit tests with Jest and Enzyme 👍.
Jest and Enzyme are different but complimentary tools, that integrate well together to provide flexible and creative testing abilities. We will briefly look at the differences between the two.

Kindly follow the blog to learn more about it.
- https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675

**Comment by divyanshu-rawat** [comment]
@marcelorl sure go ahead 👍 

Feel free to add few examples I guess by adding tests for some components!

**Comment by debck** [comment]
I would like to write unit test for some component

**Comment by divyanshu-rawat** [comment]
@debck go on 👍
