### ISSUE TITLE
Add PropTypes

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#39]
There are three popular ways to handle types in React: PropTypes, TypeScript and Flow.

Follow medium blog to know more 👍 

- https://medium.freecodecamp.org/react-pattern-centralized-proptypes-f981ff672f3b

**Comment by shaminmeerankutty** [comment]
@divyanshu-rawat I can add Proptypes to this project.

**Comment by divyanshu-rawat** [comment]
@shaminmeerankutty  sure you can take this up 👍

**Comment by shaminmeerankutty** [comment]
@divyanshu-rawat I have a pull request can you please check that one?

**Comment by divyanshu-rawat** [comment]
@shaminmeerankutty sure 👍

**Comment by TashaPenwellHC** [comment]
Is this issue still open and is @shaminmeerankutty - I can't really tell from the comments.  Thanks!

**Comment by divyanshu-rawat** [comment]
@TashaPenwellHC browse through the components in the project and if you find any component that lacks propTypes, feel free to add PropTypes in that component 👍

**Comment by CDharmateja** [comment]
I would like to work on this.

**Comment by Paarmita** [comment]
@CDharmateja Sure Go ahead!
