### ISSUE TITLE
Airbnb JavaScript Style Guide

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#43]
Airbnb maintains a very popular JavaScript Style Guide that is used by many JavaScript developers worldwide. Following this style guide will ensure your code has a level of clarity that makes reading and maintaining your code easier for anyone who has to work on it.

ESLint is a tool for “linting” your code. It can analyze your code and warn you of potential errors. In order for it to work, you need to configure it with specific rules. Luckily, Airbnb — as part of their style guide — provides an ESLint configuration that anyone can use

Follow the thread to know more 👍 
- https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6

**Comment by kabollinger** [comment]
Hi, I enjoy whitespace/style refactors and would like to work on this, but I am having trouble deciphering what the problem is and how I can help. Can you explain what I can do for you please?

**Comment by divyanshu-rawat** [comment]
@kabollinger, Thanks for your Interest, I was thinking of adding airbnb style guidelines for css,js. Apart from that if you want to do style refactors in js, css then you are most welcome to do so.
Go ahead 👍 .
Let me know if you have any other Questions 😄
