### ISSUE TITLE
Add bootstrap, jquery and popper by npm module

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#47]
**Is your feature request related to a problem? Please describe.**
Initially, they are added in index.html with the script and link tags.

**Describe the solution you'd like**
Bootstrap(latest version 4.1), jquery for bootstrap and popper should be included with npm module and the links should be removed.

https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/112382df025d0947d06f1dd9d6f06fd6fb8c5b76/public/index.html#L25

https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/112382df025d0947d06f1dd9d6f06fd6fb8c5b76/public/index.html#L19

https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/112382df025d0947d06f1dd9d6f06fd6fb8c5b76/public/index.html#L22

**Comment by mx0c** [comment]
on it :)

**Comment by vindu939** [comment]
@Paarmita Since the issue was open I raised a PR,please go through them and merge it if it solves your purpose.
