### ISSUE TITLE
HyperLinks To Jump To Specific Sections

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#5]
**Describe the bug**
Create HyperLinks to jump to specific sections on the page.
As of now when you click on any of the Link in navigation-bar it doesn't take you to specfic sections in the page.

**To Reproduce**
1. Go to www.ignitus.org.
2. Click on Links at Navigation Bar.
3. Scroll down to check whether it works or not.
4. Validate the problem yourself.

**Expected behavior**

**Screenshots**

![screen shot 2018-07-05 at 10 09 22 am](https://user-images.githubusercontent.com/13464678/42302901-86c2fd68-803b-11e8-91ab-edef7c41d479.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, MacOS]
 - Browser [e.g. chrome, safari etc]

**Smartphone :**
 - Device: All Devices
 - OS: All OS
 - Browser [e.g. stock browser, safari etc]

**Additional context**
Please Visit - www.ignitus.org

**Comment by shoutoutloud** [comment]
Hi. Can I work on this issue ?

**Comment by divyanshu-rawat** [comment]
@shoutoutloud yes 👍

**Comment by Shreya4444** [comment]
hey why have you sent this github link?

What am I supposed to do from there?


________________________________

**Comment by divyanshu-rawat** [comment]
@Shreya4444 didn't get you?

**Comment by shoutoutloud** [comment]
Thanks @divyanshu-rawat @Paarmita .Can you please guide me on what do I have to do?

**Comment by Paarmita** [comment]
@shoutoutloud Create HyperLinks to jump to a section like 'How it works?' link takes to the section 'what we do?'

**Comment by shoutoutloud** [comment]
How can I run the project on my local machine?

**Comment by Paarmita** [comment]
@shoutoutloud see [CONTRIBUTION.md](https://github.com/Ignitus/Ignitus-Client-Side-Development/blob/master/CONTRIBUTION.md)

**Comment by shoutoutloud** [comment]
Can you tell me where would `Features` and `Why Ignitus?` point to?

**Comment by Paarmita** [comment]
@shoutoutloud I will let u know till then u can work on How it works?

**Comment by shoutoutloud** [comment]
Sure.

**Comment by shoutoutloud** [comment]
@Paarmita I have made a pull request. Please have a look.
