### ISSUE TITLE
Add proper URL to the Links section on footer

### ISSUE THREAD

**Issue by debck** [Ignitus/Ignitus-Client-Side-Development#50]
**Describe the bug**
The Links in the footer doesn't render to correct page.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by louillustrator** [comment]
I will take a look at this. :)

**Comment by nirmalks** [comment]
Is this only for the URL's present under "Links" column (About us link)? If not to which URL's should "features" links and some of "community" links point to?
