### ISSUE TITLE
ShouldComponentUpdate

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#53]
In Testimonial.js we have a carousel for testimonial, that is updating/ calling componentDidUpdate on every slide change, as activeslide is getting changed.
So, we want a way to not update componentDidUpdate on every slidechange because it doesn't make sense.

![screen shot 2018-10-07 at 10 59 46 am](https://user-images.githubusercontent.com/13464678/46578520-25fe7f00-ca20-11e8-87cd-da01042c3cfc.png)

**Comment by razi-ed** [comment]
can i claim this please?

**Comment by divyanshu-rawat** [comment]
@razi-ed sure 👍

**Comment by Bharat23** [comment]
Can I claim this issue?

**Comment by ATLowther** [comment]
It looks like maybe this issue should be closed? @divyanshu-rawat
