### ISSUE TITLE
Fix ESLINT Warnings

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#54]
On running ```npm run lint``` ESLINT is showing 1081 problems (1075 errors, 6 warnings)
 621 errors and 0 warnings potentially fixable with the `--fix` option.
Fix as much as you can then feel free to send the PR.
We will be more than happy to merge it 👍 

![screen shot 2018-10-07 at 11 05 29 am](https://user-images.githubusercontent.com/13464678/46578578-fdc35000-ca20-11e8-8be0-87642b1070e8.png)

**Comment by sinha-p** [comment]
i can also help on this..

**Comment by darrylsepeda** [comment]
@divyanshu-rawat I have created pull request for this issue, please kindly review.

**Comment by akshaygulhane** [comment]
I will try to fix some ESLint warnings.

**Comment by divyanshu-rawat** [comment]
@akshaygulhane go ahead 👍

**Comment by akshataw** [comment]
I would like to work on this if the issue is open.

**Comment by akshataw** [comment]
@divyanshu-rawat  Can I work on this issue, if it is open?
