### ISSUE TITLE
Add SCSS to the project

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#58]
**Is your feature request related to a problem? Please describe.**
Add SCSS to keep things organised and allows you to create style sheets faster

**Describe the solution you'd like**
Add SCSS to the project.

**Describe alternatives you've considered**
We already have css written in the project for every component, wouldn't it be great if we can repalce css in some components or in all components and write scss for the same and then when application starts compile them to css.

**Additional context**
Sass is the most mature, stable, and powerful professional grade CSS extension language in the world.

**Comment by WolfKay** [comment]
Hello!, I would like to contribute with your project Can I take this Issue? :)

**Comment by divyanshu-rawat** [comment]
@WolfKay are you working on this?

**Comment by meyfleur** [comment]
anyone may can help with that?

**Comment by divyanshu-rawat** [comment]
@meyfleur would you like to take it?

**Comment by Martskin** [comment]
PR opened for this issue here:
https://github.com/Ignitus/Ignitus-Client-Side-Development/pull/126

**Comment by meyfleur** [comment]
i think this issue could be closed? scss is already added to the project :)

**Comment by Paarmita** [comment]
🖒
