### ISSUE TITLE
Change UI for Login/Signup

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#66]
**Describe the bug**
Update UI of Login/Logout page, follow the link to know more - http://www.ignitus.org/signup/professor

**Expected behavior**
below-mentioned screenshot is the UI of updated UI.

![screenshot from 2018-07-16 18-46-12](https://user-images.githubusercontent.com/26546816/46672298-abd32380-cbf4-11e8-95e3-0689ff42b909.png)

**Comment by meyfleur** [comment]
i can have a look on it

**Comment by Paarmita** [comment]
@meyfleur We have not integrated the button with backend API. You only need to change the UI for it 👍

**Comment by LazzyGuy** [comment]
@meyfleur  can I work on the UI too?

**Comment by Paarmita** [comment]
@LazzyGuy Thanks for the interest :) but this issue has been resolved by @meyfleur. You could take up other issues 👍
