### ISSUE TITLE
Get Navigation and Footer component out

### ISSUE THREAD

**Issue by outsourcegb** [Ignitus/Ignitus-Client-Side-Development#71]
**Is your feature request related to a problem? Please describe.**
Navigation and Footer components are being added in all other components. 
We should take them out may be in App component.

**Describe the solution you'd like**
The code is redundant.
And we should only call main component at somewhere.  

**Describe alternatives you've considered**
As mentioned we can update App component such that header and footer remains same and only main content gets changed.

**Comment by meyfleur** [comment]
i can work on this

**Comment by divyanshu-rawat** [comment]
@meyfleur go ahead 👍

**Comment by karan171996** [comment]
can i work on this ?

**Comment by outsourcegb** [comment]
@Paarmita and @karan171996 , it seems be handled already. There is a PR for the same with some conflicts.  
https://github.com/Ignitus/Ignitus-Client-Side-Development/pull/73

**Comment by divyanshu-rawat** [comment]
@outsourcegb that PR seems to have much conflicts and she have also deleted sagas.js selectors.js etc files inside every folder that are not meant to be deleted, so I guess @karan171996 can go ahead with this. what do you think @outsourcegb ?

**Comment by meyfleur** [comment]
no problem to put it back in
maybe good to consider there is a lot of duplicated code in the project which should be cleaned up

**Comment by divyanshu-rawat** [comment]
@meyfleur feel free to cleanup ir-releavent code but do not delete any exisiting file :)
