### ISSUE TITLE
Implement Aboutus and Team UI in ReactJS

### ISSUE THREAD

**Issue by Paarmita** [Ignitus/Ignitus-Client-Side-Development#75]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source contributors and current team attached UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI of About Us and Team in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer [UI Toolkit](https://github.com/Ignitus/Ignitus-UI-Kit) for User-Interface and other styles related issue.

![about page](https://user-images.githubusercontent.com/26546816/46717932-3b291700-cc87-11e8-928a-0ec9be059f7d.png)

**Comment by divyanshu-rawat** [comment]
kindly let us if you need graphics/Images for the mentioned UI.

**Comment by meyfleur** [comment]
i could work on it and maybe also on #58 as I prefer using scss if this issue is still not resolved.
Who designed the nice profile images? :D

**Comment by divyanshu-rawat** [comment]
@meyfleur If you are interested in helping Ignitus kindly join our slack channel 👍 .
Kindly join our slack (https://goo.gl/RCeffA) channel for further communication on design and development of this project,once you join let us know, it's great that you would like to work on it.

**Comment by divyanshu-rawat** [comment]
@Paarmita , @nefouci are working on UI design as of now 👍

**Comment by meyfleur** [comment]
a lot of components have /Containers/TestimonialContainer.js but it is only used in the App.js,
so if they are not necessary i would suggest to remove it everywhere.
same for the files actions, reducer, .etc which all refer to the testimonial or have no functionality. Is there a special reason for it?

**Comment by divyanshu-rawat** [comment]
Actually there is a special reason to do that, as if you can see we are making use of selectors.js, reducers.js actionTypes.js etc in testimonials, so as of now it's boilerplate 👍 but we will soon make use of them in almost every component that communicates with rest API. I hope you understand :)

**Comment by meyfleur** [comment]
can be closed too :D

**Comment by divyanshu-rawat** [comment]
sure @meyfleur 👍 apart from then if you think of any feature that we should add or any module like redux-persists for persisting data, then feel free to open the issue fot the same. 👍
