### ISSUE TITLE
Implement Introduction UI

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#85]
**Is your feature request related to a problem? Please describe.**
As per the Ignitus open source contributors and current team attached UI Design is looking for graceful and stylish in appearance, then the current one.

**Describe the solution you'd like**
Implementation of attached UI (Header, Footer, What we provide, Introduction) sections of Landing Page in terms of components, in client-side library React.js, and UI Framework Bootstrap 3/4.

**Describe alternatives you've considered**
We have updated out client-side UI design, We are looking forward to implementing the attached User-interface in react.js, Bootstrap 3/4.

**Additional context**
Refer UI Toolkit for User-Interface and other styles-related issue.

Current USER-INTERFACE
![screen shot 2018-10-13 at 12 13 02 am](https://user-images.githubusercontent.com/13464678/46888003-d46d4e80-ce7c-11e8-9674-73ed1e8f3cae.png)

EXPECTED-INTERFACE
![screen shot 2018-10-13 at 12 15 54 am](https://user-images.githubusercontent.com/13464678/46888133-3c239980-ce7d-11e8-8f63-8215b73bdd27.png)

**Comment by agoiabel** [comment]
Do you have the sketch file or adobexd file for the expected UI?

**Comment by divyanshu-rawat** [comment]
@agoiabel this UI has to be implemented in html/css/react.js this has been designed using figma?
If you need the file @Paarmita can help 👍

**Comment by agoiabel** [comment]
@Paarmita, Can you give me the link to the designed in figma ?

**Comment by Paarmita** [comment]
@agoiabel You can see the prototypes here: https://goo.gl/5NvmBe

**Comment by agoiabel** [comment]
I have seen it, I must say the design looks great. I think we need a mobile version for every screen, as I code using the mobile first approach.

**Comment by divyanshu-rawat** [comment]
@Trip4077 can you look into this? this is the only UI left in homepage 😄

**Comment by Trip4077** [comment]
@divyanshu-rawat Sure thing 👍
