### ISSUE TITLE
Prevent unnecessary state updates.

### ISSUE THREAD

**Issue by divyanshu-rawat** [Ignitus/Ignitus-Client-Side-Development#88]
Testimonial state is getting updated on every slide, can we figure out a way to prevent unnecessary state update. 👍 

![screen shot 2018-10-14 at 1 38 45 pm](https://user-images.githubusercontent.com/13464678/46914101-a55af800-cfb6-11e8-9a34-fcf4146ceea8.png)

**Comment by razi-ed** [comment]
can i claim this?

**Comment by outsourcegb** [comment]
@razi-ed , Sure

**Comment by divyanshu-rawat** [comment]
Thanks @razi-ed  it works Thanks for the PR 👍

**Comment by razi-ed** [comment]
welcome :)

**Comment by divyanshu-rawat** [comment]
#53 solved this 👍
